# Generated by Django 4.2.5 on 2024-11-29 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField()),
                ('tujuan', models.TextField()),
                ('proses_bisnis', models.CharField(max_length=255)),
                ('kelompok_resiko', models.CharField(max_length=255)),
                ('kode_resiko', models.CharField(max_length=255)),
                ('penyebab_resiko', models.TextField()),
                ('sumber_resiko', models.BooleanField()),
                ('akibat', models.TextField()),
                ('akibat_finansial', models.IntegerField()),
                ('pemilik_resiko', models.CharField(max_length=255)),
                ('departemen', models.CharField(max_length=255)),
                ('inherent_likelihood', models.IntegerField()),
                ('inherent_impact', models.IntegerField()),
                ('inherent_score', models.IntegerField()),
                ('control', models.BooleanField()),
                ('memadai', models.BooleanField()),
                ('status', models.BooleanField()),
                ('residual_likelihood', models.IntegerField()),
                ('residual_impact', models.IntegerField()),
                ('residual_score', models.IntegerField()),
                ('perlakuan', models.BooleanField()),
                ('tindakan_mitigasi', models.TextField()),
                ('mitigasi_likelihood', models.IntegerField()),
                ('mitigasi_impact', models.IntegerField()),
                ('mitigasi_score', models.IntegerField()),
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
                ('total_modifikasi', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField()),
                ('password', models.TextField()),
                ('namalengkap', models.CharField(blank=True, default='Unknown', max_length=300, null=True)),
                ('nomor_induk', models.CharField(default=None, max_length=50, null=True)),
                ('jabatan', models.CharField(default=None, max_length=100)),
                ('gelar', models.CharField(blank=True, default='Unknown', max_length=100, null=True)),
                ('alamat', models.TextField(default=None)),
                ('tanggal_lahir', models.DateField(default=None)),
                ('foto', models.ImageField(blank=True, default='user_photos/herta.jpg', null=True, upload_to='user_photos/')),
                ('total_pengisian', models.IntegerField(default=0)),
            ],
        ),
    ]
