# Generated by Django 4.2.5 on 2024-11-22 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rizzman', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='user',
            field=models.TextField(),
        ),
    ]
