# Generated by Django 4.2.5 on 2024-11-22 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rizzman', '0003_userprofile_password_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='alamat',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='foto',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='user_photos/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='jabatan',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nomor_induk',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tanggal_lahir',
            field=models.DateField(default=None),
        ),
    ]
