# Generated by Django 4.2 on 2024-11-30 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rizzman', '0004_alter_userprofile_alamat_alter_userprofile_foto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='risk',
            name='sumber_resiko',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='password',
        ),
        migrations.AlterField(
            model_name='risk',
            name='akibat_finansial',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='risk',
            name='inherent_impact',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='risk',
            name='inherent_likelihood',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='risk',
            name='inherent_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='risk',
            name='kelompok_resiko',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='risk',
            name='kode_resiko',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='risk',
            name='memadai',
            field=models.BooleanField(choices=[(True, 'Memadai'), (False, 'Tidak Memadai')]),
        ),
        migrations.AlterField(
            model_name='risk',
            name='mitigasi_impact',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='risk',
            name='mitigasi_likelihood',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='risk',
            name='mitigasi_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='risk',
            name='proses_bisnis',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='risk',
            name='residual_impact',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='risk',
            name='residual_likelihood',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='risk',
            name='residual_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='risk',
            name='status',
            field=models.BooleanField(choices=[(True, 'Active'), (False, 'Inactive')], default=True),
        ),
        migrations.AlterField(
            model_name='risk',
            name='total_modifikasi',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='risk',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='alamat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='user_photos/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='jabatan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nomor_induk',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tanggal_lahir',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='total_pengisian',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='risk',
            name='departemen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risks', to='rizzman.department'),
        ),
    ]
