# Generated by Django 4.2 on 2024-12-01 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rizzman', '0005_department_remove_risk_sumber_resiko_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='nomor_induk',
            new_name='nama',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='gelar',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='foto',
            field=models.ImageField(blank=True, default='herta.jpg', null=True, upload_to='user_photos/'),
        ),
    ]
