# Generated by Django 4.2 on 2024-12-01 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rizzman', '0006_rename_nomor_induk_userprofile_nama_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='sumber_resiko',
            field=models.CharField(choices=[('internal', 'Internal'), ('external', 'External'), ('both', 'Internal dan External')], default='internal', max_length=100),
        ),
    ]
