# Generated by Django 4.2 on 2024-12-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rizzman', '0007_risk_sumber_resiko'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bisnis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kelompok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='risk',
            name='control',
            field=models.BooleanField(choices=[(True, 'Ada'), (False, 'Tidak')]),
        ),
        migrations.AlterField(
            model_name='risk',
            name='kelompok_resiko',
            field=models.CharField(default='Null', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='risk',
            name='perlakuan',
            field=models.BooleanField(choices=[(True, 'Accept'), (True, 'Reduce')]),
        ),
        migrations.AlterField(
            model_name='risk',
            name='proses_bisnis',
            field=models.CharField(default='Null', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='risk',
            name='sumber_resiko',
            field=models.CharField(choices=[('internal', 'Internal'), ('external', 'External'), ('both', 'Internal dan External')], max_length=100),
        ),
    ]
