# Generated by Django 4.2 on 2024-12-01 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rizzman', '0008_bisnis_kelompok_alter_risk_control_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='kelompok_resiko',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risks', to='rizzman.kelompok'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='proses_bisnis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risks', to='rizzman.bisnis'),
        ),
    ]
