# Generated by Django 4.2 on 2024-12-01 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rizzman', '0009_alter_risk_kelompok_resiko_alter_risk_proses_bisnis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('priority', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='jabatan',
            field=models.ForeignKey(blank=True, default=None, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rizzman.role'),
        ),
    ]
