# Generated by Django 4.2 on 2024-12-02 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rizzman', '0010_role_alter_userprofile_jabatan'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='tingkat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='risk',
            name='status',
            field=models.BooleanField(choices=[(True, 'Executed'), (False, 'Ongoing')]),
        ),
    ]
