# Generated by Django 4.2 on 2024-12-03 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rizzman', '0011_risk_tingkat_alter_risk_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='uraian_peristiwa',
            field=models.TextField(default='Kosong'),
            preserve_default=False,
        ),
    ]
