# Generated by Django 4.2 on 2024-12-06 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rizzman', '0012_risk_uraian_peristiwa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='perlakuan',
            field=models.CharField(choices=[('accept', 'Accept'), ('reduce', 'Reduce'), ('avoid', 'Avoid'), ('share', 'Share')], max_length=50),
        ),
    ]
