# Generated by Django 4.2 on 2024-12-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rizzman', '0016_alter_risk_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='status',
            field=models.CharField(choices=[('executed', 'Executed'), ('ongoing', 'Ongoing'), ('pending', 'Pending')], default='Pending', max_length=50),
            preserve_default=False,
        ),
    ]
